% -------------------------------------------------------------------
%  Generated by MATLAB on 30-Mar-2026 13:03:53
%  MATLAB version: 25.2.0.3150157 (R2025b) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('code.mat');

I1 = saveVarsMat.I1; % <256x256 uint8> too many elements

I1_gauss = saveVarsMat.I1_gauss; % <256x256 uint8> too many elements

I1_high = saveVarsMat.I1_high; % <256x256 uint8> too many elements

I1_low = saveVarsMat.I1_low; % <256x256 uint8> too many elements

I1_sp = saveVarsMat.I1_sp; % <256x256 uint8> too many elements

I2 = saveVarsMat.I2; % <246x300 uint8> too many elements

I2_gauss = saveVarsMat.I2_gauss; % <246x300 uint8> too many elements

I2_sp = saveVarsMat.I2_sp; % <246x300 uint8> too many elements

I_gauss_low = saveVarsMat.I_gauss_low; % <256x256 uint8> too many elements

I_median = saveVarsMat.I_median; % <256x256 uint8> too many elements

I_sp_low = saveVarsMat.I_sp_low; % <256x256 uint8> too many elements

I_wiener = saveVarsMat.I_wiener; % <256x256 uint8> too many elements

h_high = ...
  [0.16666666666666669 0.66666666666666674 0.16666666666666669;
   0.66666666666666674 -3.3333333333333335 0.66666666666666674;
   0.16666666666666669 0.66666666666666674 0.16666666666666669];

h_low = ...
  [0.1111111111111111 0.1111111111111111 0.1111111111111111;
   0.1111111111111111 0.1111111111111111 0.1111111111111111;
   0.1111111111111111 0.1111111111111111 0.1111111111111111];

clear saveVarsMat;
